#!/usr/bin/env bash
#
# Manage an inline "probe" Gradle module used to measure the UI SDK's
# standalone APK footprint per ABI. The probe app's only dependency is
# `:amani-sdk-v1`, so its release APK shows what users would carry if
# they integrated the SDK into an empty app.
#
# Usage:
#   probe.sh setup     # create .ci-probe/ and append include line to settings.gradle
#   probe.sh teardown  # remove .ci-probe/ and revert settings.gradle to last commit
#
# The settings.gradle modification is reverted via `git checkout` so a stale
# include from a previous failed run still gets cleaned up.
set -euo pipefail

PROBE_DIR=".ci-probe"
MARKER="// CI probe — auto-generated by .github/scripts/probe.sh"

setup() {
  mkdir -p "$PROBE_DIR/src/main/kotlin/ai/amani/probe"

  cat > "$PROBE_DIR/build.gradle" <<'EOF'
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    compileSdk 34
    namespace 'ai.amani.probe'
    defaultConfig {
        applicationId 'ai.amani.probe'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
            universalApk true
        }
    }
    sourceSets {
        main {
            java.srcDirs = []
            kotlin.srcDirs = ['src/main/kotlin']
        }
    }
    packaging {
        resources {
            excludes += [
                "META-INF/versions/9/OSGI-INF/MANIFEST.MF",
                "META-INF/*.kotlin_module",
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE*",
                "META-INF/NOTICE*",
            ]
            pickFirsts += ["META-INF/INDEX.LIST"]
        }
    }
}
dependencies {
    implementation project(':amani-sdk-v1')
}
EOF

  cat > "$PROBE_DIR/src/main/AndroidManifest.xml" <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <application
        android:label="Probe"
        android:allowBackup="false"
        tools:replace="android:label,android:allowBackup">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
EOF

  cat > "$PROBE_DIR/src/main/kotlin/ai/amani/probe/MainActivity.kt" <<'EOF'
package ai.amani.probe
import android.app.Activity
class MainActivity : Activity()
EOF

  if ! grep -q "$MARKER" settings.gradle; then
    {
      echo ""
      echo "$MARKER"
      echo "include ':probe'"
      echo "project(':probe').projectDir = file('${PROBE_DIR}')"
    } >> settings.gradle
  fi

  echo "Probe ready at ${PROBE_DIR}/"
}

teardown() {
  rm -rf "$PROBE_DIR"
  if git ls-files --error-unmatch settings.gradle > /dev/null 2>&1; then
    git checkout -- settings.gradle
  fi
  echo "Probe torn down."
}

cmd="${1:-}"
case "$cmd" in
  setup)    setup ;;
  teardown) teardown ;;
  *)        echo "usage: $0 {setup|teardown}" >&2; exit 2 ;;
esac
