#!/usr/bin/env bash
#
# Manage an inline "probe" Gradle module used to measure the UI / Core SDK's
# net APK footprint per ABI. Three product flavors:
#
#   bare     — AndroidX/Material baseline only, no Amani deps
#   withcore — baseline + Core SDK (`ai.amani.android:AmaniAi`)
#   withsdk  — baseline + UI SDK (`:amani-sdk-v1`, which transitively pulls Core)
#
# Per-ABI deltas:
#   Core SDK     = withcore − bare      (Core's net cost over an empty app)
#   UI SDK (Δ)   = withsdk  − withcore  (UI layer's marginal cost on top of Core)
#
# All flavors share the same AndroidX/Material baseline so transitive deps
# deduplicate identically — the deltas reflect SDK content, not packaging noise.
#
# The Core SDK version is read dynamically from amani-sdk-v1/build.gradle so
# probe always matches what the UI SDK pulls.
#
# Usage:
#   probe.sh setup     # create .ci-probe/ and append include line to settings.gradle
#   probe.sh teardown  # remove .ci-probe/ and revert settings.gradle to last commit
#
# The settings.gradle modification is reverted via `git checkout` so a stale
# include from a previous failed run still gets cleaned up.
set -euo pipefail

PROBE_DIR=".ci-probe"
MARKER="// CI probe — auto-generated by .github/scripts/probe.sh"

setup() {
  mkdir -p "$PROBE_DIR/src/main/kotlin/ai/amani/probe"

  AMANI_CORE_VERSION=$(grep -E '^\s*def\s+amani_sdk\s*=' amani-sdk-v1/build.gradle \
    | sed -E 's/.*"([^"]+)".*/\1/')
  if [ -z "$AMANI_CORE_VERSION" ]; then
    echo "::error::could not read amani_sdk version from amani-sdk-v1/build.gradle" >&2
    exit 1
  fi
  echo "Using Core SDK version: $AMANI_CORE_VERSION"

  cat > "$PROBE_DIR/build.gradle" <<EOF
// Generated by .github/scripts/probe.sh — Core SDK version: ${AMANI_CORE_VERSION}
EOF
  cat >> "$PROBE_DIR/build.gradle" <<'EOF'
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-parcelize'
}
android {
    compileSdk 34
    namespace 'ai.amani.probe'
    defaultConfig {
        applicationId 'ai.amani.probe'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    buildTypes {
        release { minifyEnabled false }
    }
    flavorDimensions += "sdk"
    productFlavors {
        bare     { dimension "sdk" }
        withcore { dimension "sdk" }
        withsdk  { dimension "sdk" }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
            universalApk true
        }
    }
    sourceSets {
        main {
            java.srcDirs = []
            kotlin.srcDirs = ['src/main/kotlin']
        }
    }
    packaging {
        resources {
            excludes += [
                "META-INF/versions/9/OSGI-INF/MANIFEST.MF",
                "META-INF/*.kotlin_module",
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE*",
                "META-INF/NOTICE*",
            ]
            pickFirsts += ["META-INF/INDEX.LIST"]
        }
    }
}
dependencies {
    // Shared baseline mirroring :app — all flavors pull the same AndroidX/Material
    // versions, so transitive AndroidX deps deduplicate identically across APKs.
    // Without this, deltas are polluted by dep-version drift.
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    withcoreImplementation "ai.amani.android:AmaniAi:__AMANI_CORE_VERSION__"
    withsdkImplementation  project(':amani-sdk-v1')
}
EOF

  # Inject Core SDK version (read above from amani-sdk-v1/build.gradle)
  sed -i.bak "s/__AMANI_CORE_VERSION__/${AMANI_CORE_VERSION}/g" "$PROBE_DIR/build.gradle"
  rm -f "$PROBE_DIR/build.gradle.bak"

  cat > "$PROBE_DIR/src/main/AndroidManifest.xml" <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <application
        android:label="Probe"
        android:allowBackup="false"
        tools:replace="android:label,android:allowBackup">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
EOF

  cat > "$PROBE_DIR/src/main/kotlin/ai/amani/probe/MainActivity.kt" <<'EOF'
package ai.amani.probe
import android.app.Activity
class MainActivity : Activity()
EOF

  if ! grep -q "$MARKER" settings.gradle; then
    {
      echo ""
      echo "$MARKER"
      echo "include ':probe'"
      echo "project(':probe').projectDir = file('${PROBE_DIR}')"
    } >> settings.gradle
  fi

  echo "Probe ready at ${PROBE_DIR}/"
}

teardown() {
  rm -rf "$PROBE_DIR"
  if git ls-files --error-unmatch settings.gradle > /dev/null 2>&1; then
    git checkout -- settings.gradle
  fi
  echo "Probe torn down."
}

cmd="${1:-}"
case "$cmd" in
  setup)    setup ;;
  teardown) teardown ;;
  *)        echo "usage: $0 {setup|teardown}" >&2; exit 2 ;;
esac
