#!/usr/bin/env python3
"""
Maintain .github/metrics/SIZE_HISTORY.md.

Given a freshly-generated `--section` markdown (produced by measure_apk.py)
and a `--version` label, this script:

  1. Replaces (or inserts) the row for that version in the top "AAR size trend"
     table — keeping the table sorted with newest first by date.
  2. Removes any pre-existing per-release section for that version.
  3. Inserts the new per-release section at the top of the per-release area.

The history file is created with the canonical header if it doesn't exist.
The trend table's "Δ vs prev" column is recomputed for the inserted row only;
older rows keep whatever delta they had recorded at write time.
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path

HEADER = """# AAR / APK Size History

Tracks the SDK's per-ABI footprint across releases. Generated by **③ Release · Ship** (on every published release) and **④ Release · Measure** (manual trigger, or for backfill).

> **Method:** SDK contribution is measured via an inline probe app with two flavors — `bare` (AndroidX/Material baseline, no SDK) and `withsdk` (same baseline + `:amani-sdk-v1`). The delta isolates the SDK's net cost. Sizes are measured in CI on `ubuntu-latest` with JDK 17 (matching `jitpack.yml`) against **release** build variants — debug builds are typically 1.5–3× larger due to retained debug symbols and are intentionally not tracked. The artifact JitPack serves to consumers may differ slightly because JitPack performs its own build.
>
> ⚠️ **APK figures are approximate (~0.1–0.5 MB run-to-run variance)** — APK builds are not perfectly reproducible (signing entropy, baseline profiles, ZIP ordering). Treat the per-ABI numbers as **trend signals**, not exact byte budgets. The AAR row in the trend table is more stable.

---

## AAR size trend

At-a-glance view of `:amani-sdk-v1` AAR size across releases — useful for separating SDK-only regressions from APK-level regressions caused by transitive dependency updates.

| Version | AAR | Δ vs prev | Date (UTC) |
|---------|----:|----------:|------------|

---

## Per-release breakdown

"""

TREND_HEADER = "| Version | AAR | Δ vs prev | Date (UTC) |"
TREND_SEP    = "|---------|----:|----------:|------------|"


def parse_section(section: str) -> tuple[str, int]:
    """Extract (date_str, aar_bytes) from a generated section."""
    m = re.search(r"^## .+? — (\d{4}-\d{2}-\d{2})", section, re.MULTILINE)
    date = m.group(1) if m else ""
    m = re.search(r"\(`([\d,]+)` bytes\)", section)
    if not m:
        raise SystemExit("Cannot find AAR bytes in section markdown")
    return date, int(m.group(1).replace(",", ""))


def fmt_mb(b: int) -> str:
    return f"{b/1048576:.2f} MB"


def fmt_signed_kb(b: int) -> str:
    sign = "+" if b >= 0 else "−"
    return f"{sign}{abs(b)/1024:.0f} KB"


def update_trend(text: str, version: str, date: str, aar_bytes: int) -> str:
    """Replace/insert the row for `version` in the trend table."""
    lines = text.splitlines(keepends=False)

    # Locate trend table separator
    try:
        sep_idx = next(i for i, ln in enumerate(lines) if ln.strip() == TREND_SEP)
    except StopIteration:
        return text  # no trend table; nothing to do

    # Find table body bounds
    body_start = sep_idx + 1
    body_end = body_start
    while body_end < len(lines) and lines[body_end].lstrip().startswith("|"):
        body_end += 1

    # Parse existing rows: [(version, exact_bytes_or_None, raw_line)]
    # Exact bytes are stored as an HTML comment in the version cell so the
    # rendered table stays clean while letting us compute precise deltas.
    parsed: list[tuple[str, int | None, str]] = []
    for ln in lines[body_start:body_end]:
        cells = [c.strip() for c in ln.strip().strip("|").split("|")]
        if len(cells) >= 1 and cells[0]:
            v_cell = cells[0]
            v = re.sub(r"\s*<!--.*?-->\s*", "", v_cell).strip()
            byte_match = re.search(r"<!--\s*bytes=(\d+)\s*-->", v_cell)
            if byte_match:
                ab = int(byte_match.group(1))
            else:
                # Fallback: derive from "X.XX MB" cell (loses precision)
                mb_match = re.search(r"([\d.]+)\s*MB", cells[1] if len(cells) > 1 else "")
                ab = int(float(mb_match.group(1)) * 1048576) if mb_match else None
            parsed.append((v, ab, ln))

    # Drop any existing row for this version
    parsed = [r for r in parsed if r[0] != version]

    # Compute delta vs previous newest row using exact bytes when available
    delta = "—" if not parsed else fmt_signed_kb(aar_bytes - (parsed[0][1] or aar_bytes))
    new_row = f"| {version} <!-- bytes={aar_bytes} --> | {fmt_mb(aar_bytes)} | {delta} | {date} |"

    new_body = [new_row] + [r[2] for r in parsed]
    return "\n".join(lines[:body_start] + new_body + lines[body_end:]) + "\n"


def update_sections(text: str, version: str, section: str) -> str:
    """Remove any existing `### {version}` block and prepend the new section."""
    # Remove any "### <version> — ..." block up to the next "### " or EOF
    pattern = re.compile(
        r"^### " + re.escape(version) + r" — .*?(?=^### |\Z)",
        re.DOTALL | re.MULTILINE,
    )
    text = pattern.sub("", text)

    # Convert the generated section's "## " heading to "### " (per-release subheading)
    section = re.sub(r"^## ", "### ", section, count=1, flags=re.MULTILINE)
    section = section.rstrip() + "\n\n"

    # Insert immediately after "## Per-release breakdown\n\n"
    marker = "## Per-release breakdown\n\n"
    if marker in text:
        head, _, tail = text.partition(marker)
        return head + marker + section + tail
    return text.rstrip() + "\n\n" + section


def update_json_outputs(
    measurement: dict,
    latest_path: Path,
    history_path: Path,
) -> None:
    version = measurement["version"]

    releases: list[dict] = []
    if history_path.exists():
        try:
            existing = json.loads(history_path.read_text())
            releases = [r for r in existing.get("releases", []) if r.get("version") != version]
        except (json.JSONDecodeError, KeyError):
            releases = []

    prev_aar = releases[0]["aar"]["bytes"] if releases else None
    cur_aar = measurement["aar"]["bytes"]
    delta_vs_prev = None if prev_aar is None else cur_aar - prev_aar

    latest = dict(measurement)
    latest["deltaVsPrev"] = {"aarBytes": delta_vs_prev}

    releases.insert(0, dict(measurement))

    history = {
        "schemaVersion": 1,
        "updatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "releases": releases,
    }

    latest_path.parent.mkdir(parents=True, exist_ok=True)
    latest_path.write_text(json.dumps(latest, indent=2) + "\n")
    history_path.write_text(json.dumps(history, indent=2) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--section", required=True, type=Path, help="path to section markdown")
    ap.add_argument("--history", default=".github/metrics/SIZE_HISTORY.md", type=Path)
    ap.add_argument(
        "--measurement-json",
        type=Path,
        help="per-run measurement JSON produced by measure_apk.py; "
        "when provided, size-latest.json and size-history.json are written",
    )
    ap.add_argument("--latest-json", default=".github/metrics/size-latest.json", type=Path)
    ap.add_argument("--history-json", default=".github/metrics/size-history.json", type=Path)
    args = ap.parse_args()

    section_text = args.section.read_text()
    date, aar_bytes = parse_section(section_text)

    if not args.history.exists():
        args.history.parent.mkdir(parents=True, exist_ok=True)
        args.history.write_text(HEADER)

    text = args.history.read_text()
    text = update_trend(text, args.version, date, aar_bytes)
    text = update_sections(text, args.version, section_text)
    args.history.write_text(text)
    print(f"Updated {args.history}: trend row + per-release section for {args.version}")

    if args.measurement_json and args.measurement_json.exists():
        measurement = json.loads(args.measurement_json.read_text())
        update_json_outputs(measurement, args.latest_json, args.history_json)
        print(f"Updated {args.latest_json} and {args.history_json}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
